DROP TABLE "TB_MBR";

CREATE TABLE "TB_MBR" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"EMAIL"	VARCHAR2(64)		NOT NULL,
	"PASSWD"	VARCHAR2(64)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"MBR_NM"	VARCHAR2(64)		NOT NULL,
	"GENDER"	CHAR(1)		NOT NULL,
	"PHONE"	VARCHAR2(64)		NOT NULL,
	"POST"	VARCHAR2(64)		NOT NULL,
	"ADDR1"	VARCHAR2(256)		NOT NULL,
	"ADDR2"	VARCHAR2(256)		NOT NULL,
	"FLG_SMS"	CHAR(1)		NOT NULL,
	"DT_SMS"	DATE		NOT NULL,
	"FLG_EMAIL"	CHAR(1)		NOT NULL,
	"DT_EMAIL"	DATE		NOT NULL,
	"LAST_IP"	VARCHAR2(16)		NULL,
	"LAST_DT"	DATE		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MBR"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_MBR"."EMAIL" IS '이메일(아이디)';

COMMENT ON COLUMN "TB_MBR"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MBR"."CD_STATE" IS '상태 코드:  대기(0), 사용중(1), 자퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_MBR"."MBR_NM" IS '성명';

COMMENT ON COLUMN "TB_MBR"."GENDER" IS '성별: 남자(M), 여자(F)';

COMMENT ON COLUMN "TB_MBR"."PHONE" IS '연락처(예: 010-1111-2222)';

COMMENT ON COLUMN "TB_MBR"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MBR"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MBR"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MBR"."FLG_SMS" IS '수신여부 SMS';

COMMENT ON COLUMN "TB_MBR"."DT_SMS" IS '수신여부 SMS 일시';

COMMENT ON COLUMN "TB_MBR"."FLG_EMAIL" IS '수신여부 EMAIL';

COMMENT ON COLUMN "TB_MBR"."DT_EMAIL" IS '수신여부  EMAIL 일시';

COMMENT ON COLUMN "TB_MBR"."LAST_IP" IS '마지막 로그인 IP';

COMMENT ON COLUMN "TB_MBR"."LAST_DT" IS '마지막 로그인 일시';

COMMENT ON COLUMN "TB_MBR"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_MBR"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MBR"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_MBR"."UPDATER" IS '수정자';

DROP TABLE "TB_TRM_AGR";

CREATE TABLE "TB_TRM_AGR" (
	"SEQ_TRM_AGR"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_TRM"	NUMBER(3)		NOT NULL,
	"FLG_AGR"	CHAR(1)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM_AGR" IS '약관 동의 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."SEQ_TRM" IS '약관 일련번호';

COMMENT ON COLUMN "TB_TRM_AGR"."FLG_AGR" IS '수락 여부';

COMMENT ON COLUMN "TB_TRM_AGR"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_TRM_AGR"."REGISTER" IS '등록자';

DROP TABLE "TB_STAT_MBR";

CREATE TABLE "TB_STAT_MBR" (
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"POST"	VARCHAR2(5)		NOT NULL
);

COMMENT ON COLUMN "TB_STAT_MBR"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_STAT_MBR"."POST" IS '우편번호';

DROP TABLE "TB_SLE";

CREATE TABLE "TB_SLE" (
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(128)		NOT NULL,
	"CD_CTG"	CHAR(2)		NOT NULL,
	"CD_STATE_SALE"	CHAR(1)		NOT NULL,
	"PRICE_COST"	NUMBER(10)		NOT NULL,
	"DISCOUNT"	NUMBER(3)		NOT NULL,
	"COUNT_STOCK"	VARCHAR2(128)		NOT NULL,
	"DESCES"	VARCHAR2(2048)		NULL,
	"COLOR"	VARCHAR2(256)		NOT NULL,
	"MERTERIAL"	VARCHAR2(256)		NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"SIZE_NM"	VARCHAR2(128)		NOT NULL,
	"SIZE_DETAIL"	VARCHAR(1024)		NOT NULL,
	"HEART"	NUMBER(10)		NOT NULL,
	"REVIEW"	NUMBER(10)		NOT NULL,
	"DT_SALE_START"	DATE		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_SLE"."SEQ_SLE" IS '상품 판매 일련번호';

COMMENT ON COLUMN "TB_SLE"."SLE_NM" IS '상품명';

COMMENT ON COLUMN "TB_SLE"."CD_CTG" IS '상품 카테고리: 1(여성), 2(남성), x1(아우터),x2(재킷/베스트), x3(상의), x4(하의), x5(원피스), x6(패션잡화)';

COMMENT ON COLUMN "TB_SLE"."CD_STATE_SALE" IS '판매 상품 상태 코드: 판매(1), 품절(2), 중지(3), 반려(9)';

COMMENT ON COLUMN "TB_SLE"."PRICE_COST" IS '상품 원가';

COMMENT ON COLUMN "TB_SLE"."DISCOUNT" IS '상품 할인율';

COMMENT ON COLUMN "TB_SLE"."COUNT_STOCK" IS '재고 수량 (사이즈별로 '/' 로 구분)';

COMMENT ON COLUMN "TB_SLE"."DESCES" IS '상품 설명';

COMMENT ON COLUMN "TB_SLE"."COLOR" IS '상품 색상';

COMMENT ON COLUMN "TB_SLE"."MERTERIAL" IS '소재';

COMMENT ON COLUMN "TB_SLE"."IMG" IS '이미지(대표)';

COMMENT ON COLUMN "TB_SLE"."SIZE_NM" IS '사이즈 예)XS,S,M,L,XL,XXL,XXXL ...';

COMMENT ON COLUMN "TB_SLE"."SIZE_DETAIL" IS '사이즈 상세 예)옷길이/52/53/54,어깨너비/52/53/54,가슴둘레/106/111/116,...';

COMMENT ON COLUMN "TB_SLE"."HEART" IS '좋아요(찜) 회원당 한번만';

COMMENT ON COLUMN "TB_SLE"."REVIEW" IS '리뷰수';

COMMENT ON COLUMN "TB_SLE"."DT_SALE_START" IS '판매 시작 일시';

COMMENT ON COLUMN "TB_SLE"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_SLE"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_SLE"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_SLE"."UPDATER" IS '수정자';

DROP TABLE "TB_SLE_IMG";

CREATE TABLE "TB_SLE_IMG" (
	"SEQ_SLE_IMG"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"FLG_INFO"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE_IMG" IS '판매 상품 이미지 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."SEQ_SLE" IS '상품 일련번호';

COMMENT ON COLUMN "TB_SLE_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_SLE_IMG"."FLG_INFO" IS '상품정보이미지: Y, 기본: NULL';

COMMENT ON COLUMN "TB_SLE_IMG"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_SLE_IMG"."REGISTER" IS '등록자';

DROP TABLE "TB_BSK";

CREATE TABLE "TB_BSK" (
	"SEQ_BSK"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SLE_NM"	VARCHAR2(256)		NOT NULL,
	"SIZE_NM"	CHAR(1)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"CD_STATE_PAY"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NOT NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BSK"."SEQ_BSK" IS '장바구니 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_BSK"."SEQ_SLE" IS '판매 상품 일련번호';

COMMENT ON COLUMN "TB_BSK"."SLE_NM" IS '판매 상품명';

COMMENT ON COLUMN "TB_BSK"."SIZE_NM" IS '판매 상품 사이즈  (상품 사이즈에서 '/' 기준 인덱스 값이 들어감)';

COMMENT ON COLUMN "TB_BSK"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BSK"."COUNT" IS '구매 수량';

COMMENT ON COLUMN "TB_BSK"."IMG" IS '판매 상품 이미지';

COMMENT ON COLUMN "TB_BSK"."CD_STATE_PAY" IS '구매 완료 여부: 결제 전(NULL), 결제 완료(Y)';

COMMENT ON COLUMN "TB_BSK"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BSK"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BSK"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_BSK"."UPDATER" IS '수정자';

DROP TABLE "TB_REV";

CREATE TABLE "TB_REV" (
	"SEQ_REV"	NUMBER(10)		NOT NULL,
	"SEQ_BUY_DTL"	NUMBER(19)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLL"	NUMBER(10)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"RATING"	NUMBER(10)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"SLL_NM"	VARCHAR2(32)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"FLG_SLE_DELETE"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_REV"."SEQ_REV" IS '리뷰 상세 일련번호';

COMMENT ON COLUMN "TB_REV"."SEQ_BUY_DTL" IS '구매 상세 일련번호';

COMMENT ON COLUMN "TB_REV"."SEQ_SLE" IS '상품 판매 일련번호';

COMMENT ON COLUMN "TB_REV"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_REV"."SEQ_SLL" IS '판매자 일련번호';

COMMENT ON COLUMN "TB_REV"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_REV"."RATING" IS '평점';

COMMENT ON COLUMN "TB_REV"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_REV"."SLL_NM" IS '판매자';

COMMENT ON COLUMN "TB_REV"."FLG_DELETE" IS '삭제여부: 기본(NULL), 삭제(Y)';

COMMENT ON COLUMN "TB_REV"."FLG_SLE_DELETE" IS '상품 삭제 여부: 기본(NULL), 삭제(Y)';

COMMENT ON COLUMN "TB_REV"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_REV"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_REV"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_REV"."UPDATER" IS '수정자';

DROP TABLE "TB_BUY_MST";

CREATE TABLE "TB_BUY_MST" (
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_ACT"	NUMBER(19)		NULL,
	"BUY_INFO"	VARCHAR2(128)		NOT NULL,
	"BUY_COUNT"	NUMBER(3)		NOT NULL,
	"BUY_PRICE"	NUMBER(10)		NOT NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"CD_STATE_PAY"	CHAR(1)		NULL,
	"CD_STATE_DELIVERY"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_BUY_MST"."SEQ_ACT" IS '경매 일련번호 (경매 상품 결제 건만)';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_INFO" IS '구매 상품 정보(예: Java 외 1개 도서)';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_COUNT" IS '구매 상품 총 갯수';

COMMENT ON COLUMN "TB_BUY_MST"."BUY_PRICE" IS '구매 상품 총 금액';

COMMENT ON COLUMN "TB_BUY_MST"."FLG_DELETE" IS '삭제 여부';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_PAY" IS '결제 상태 코드: 결제 전(NULL), 실패(N), 성공(Y), 취소(C)';

COMMENT ON COLUMN "TB_BUY_MST"."CD_STATE_DELIVERY" IS '배송 상태 코드: 등록 시(NULL), 확인중(C), 배송 준비중(P), 배송중(D), 배송 완료(Y)';

COMMENT ON COLUMN "TB_BUY_MST"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BUY_MST"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BUY_MST"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_BUY_MST"."UPDATER" IS '수정자';

DROP TABLE "TB_BUY_DTL";

CREATE TABLE "TB_BUY_DTL" (
	"SEQ_BUY_DTL"	NUMBER(19)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NULL,
	"SEQ_ACT"	NUMBER(19)		NULL,
	"SIZE_NM"	CHAR(1)		NOT NULL,
	"COUNT"	NUMBER(3)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_DTL" IS '구매 상세 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_BUY_MST" IS '구매';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_SLE" IS '상품 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SEQ_ACT" IS '경매 일련번호';

COMMENT ON COLUMN "TB_BUY_DTL"."SIZE_NM" IS '판매 상품 사이즈  (상품 사이즈에서 '/' 기준 인덱스 값이 들어감)';

COMMENT ON COLUMN "TB_BUY_DTL"."COUNT" IS '판매 상품 개수';

COMMENT ON COLUMN "TB_BUY_DTL"."PRICE" IS '판매 상품 가격';

COMMENT ON COLUMN "TB_BUY_DTL"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BUY_DTL"."REGISTER" IS '등록자';

DROP TABLE "TB_BBS";

CREATE TABLE "TB_BBS" (
	"SEQ_BBS"	NUMBER(10)		NOT NULL,
	"SEQ_BBS_PARENT"	NUMBER(10)		NULL,
	"DEPTH"	CHAR(1)		NULL,
	"CD_BBS_TYPE"	NUMBER(3)		NULL,
	"TITLE"	VARCHAR2(256)		NOT NULL,
	"CD_CTG"	NUMBER(3)		NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FLG_TOP"	CHAR(1)		NULL,
	"FLG_REPLY"	CHAR(1)		NULL,
	"FLG_DELETE"	CHAR(1)		NULL,
	"READED"	NUMBER(10)		NULL,
	"FILE_SAVE"	VARCHAR2(256)		NULL,
	"FILE_ORIG"	VARCHAR2(64)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS" IS '게시판 일련번호';

COMMENT ON COLUMN "TB_BBS"."SEQ_BBS_PARENT" IS '게시판 상위 일련번호(=문의 게시판 일련번호)';

COMMENT ON COLUMN "TB_BBS"."DEPTH" IS '댓글 깊이 예)원글: NULL, 댓글: 1, 대댓글: 2, 대대댓글: 3...';

COMMENT ON COLUMN "TB_BBS"."CD_BBS_TYPE" IS '게시판 타입 코드: 구매자 공지사항(1),구매자  FAQ(2), 구매자 문의(3),판매자 공지사항(4),판매자  FAQ(5), 판매자 문의(6)';

COMMENT ON COLUMN "TB_BBS"."TITLE" IS '제목';

COMMENT ON COLUMN "TB_BBS"."CD_CTG" IS '카테고리: 가입 및 탈퇴(1), 상품(2), 구매(3), 결제(4), 배송(5), 환불(6), 기타(9)';

COMMENT ON COLUMN "TB_BBS"."CONTENT" IS '내용';

COMMENT ON COLUMN "TB_BBS"."FLG_TOP" IS '최상위 여부(공지사항)';

COMMENT ON COLUMN "TB_BBS"."FLG_REPLY" IS '답변 여부(문의)';

COMMENT ON COLUMN "TB_BBS"."FLG_DELETE" IS '삭제 여부';

COMMENT ON COLUMN "TB_BBS"."READED" IS '조회수';

COMMENT ON COLUMN "TB_BBS"."FILE_SAVE" IS '파일 저장명(경로 포함)';

COMMENT ON COLUMN "TB_BBS"."FILE_ORIG" IS '파일 원본명';

COMMENT ON COLUMN "TB_BBS"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BBS"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BBS"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_BBS"."UPDATER" IS '수정자';

DROP TABLE "TB_PAY";

CREATE TABLE "TB_PAY" (
	"SEQ_PAY"	NUMBER(19)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"CD_PG"	NUMBER(3)		NOT NULL,
	"NUM_ORDER"	VARCHAR2(64)		NOT NULL,
	"NUM_DEAL"	VARCHAR2(64)		NOT NULL,
	"CD_RESPONSE"	VARCHAR2(8)		NULL,
	"CD_PAY_METHOD"	NUMBER(3)		NULL,
	"FLG_ACT"	CHAR(1)		NOT NULL,
	"FLG_SUCCESS"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(3)		NOT NULL
);

COMMENT ON COLUMN "TB_PAY"."SEQ_PAY" IS '결제 일련번호';

COMMENT ON COLUMN "TB_PAY"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_PAY"."SEQ_MBR" IS '회원 일련번호';

COMMENT ON COLUMN "TB_PAY"."CD_PG" IS 'PG사 코드: 페이업(1)';

COMMENT ON COLUMN "TB_PAY"."NUM_ORDER" IS '주문번호';

COMMENT ON COLUMN "TB_PAY"."NUM_DEAL" IS '거래(트랜잭션) 번호';

COMMENT ON COLUMN "TB_PAY"."CD_RESPONSE" IS '응답코드';

COMMENT ON COLUMN "TB_PAY"."CD_PAY_METHOD" IS '결제 수단 코드(예: 카드, 이체 등)';

COMMENT ON COLUMN "TB_PAY"."FLG_ACT" IS '경매 여부 N: 일반 상품, Y: 경매 상품';

COMMENT ON COLUMN "TB_PAY"."FLG_SUCCESS" IS '성공 여부: 기본(NULL), 실패(N), 성공(Y)';

COMMENT ON COLUMN "TB_PAY"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_PAY"."REGISTER" IS '등록자';

DROP TABLE "TB_MNG";

CREATE TABLE "TB_MNG" (
	"SEQ_MNG"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"PASSWD"	VARCHAR2(32)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"MNG_LEVEL"	NUMBER(3)		NOT NULL,
	"MNG_NM"	VARCHAR2(32)		NOT NULL,
	"EMAIL"	VARCHAR2(32)		NOT NULL,
	"PHONE"	VARCHAR2(16)		NOT NULL,
	"POST"	VARCHAR2(8)		NULL,
	"ADDR1"	VARCHAR2(128)		NULL,
	"ADDR2"	VARCHAR2(128)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_MNG"."SEQ_MNG" IS '관리자 일련번호';

COMMENT ON COLUMN "TB_MNG"."ID" IS '아이디';

COMMENT ON COLUMN "TB_MNG"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_MNG"."CD_STATE" IS '상태코드: 대기(0), 사용=승인(1), 반려(2), 자퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_MNG"."MNG_LEVEL" IS '직급: 최고관리자(1), 그 외(9)';

COMMENT ON COLUMN "TB_MNG"."MNG_NM" IS '성명';

COMMENT ON COLUMN "TB_MNG"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_MNG"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_MNG"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_MNG"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_MNG"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_MNG"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_MNG"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_MNG"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_MNG"."UPDATER" IS '수정자';

DROP TABLE "TB_SLL";

CREATE TABLE "TB_SLL" (
	"SEQ_SLL"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(32)		NOT NULL,
	"PASSWD"	VARCHAR2(64)		NOT NULL,
	"CD_STATE"	NUMBER(3)		NOT NULL,
	"SLL_NM"	VARCHAR2(32)		NOT NULL,
	"EMAIL"	VARCHAR2(32)		NOT NULL,
	"PHONE"	VARCHAR2(16)		NOT NULL,
	"CORP_NUM"	CHAR(12)		NOT NULL,
	"CORP_NM"	VARCHAR2(64)		NOT NULL,
	"CORP_BIRTHDAY"	CHAR(8)		NOT NULL,
	"CORP_CEO"	VARCHAR2(32)		NOT NULL,
	"POST"	VARCHAR2(8)		NOT NULL,
	"ADDR1"	VARCHAR2(256)		NOT NULL,
	"ADDR2"	VARCHAR2(256)		NOT NULL,
	"INTRO"	VARCHAR2(1024)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_SLL"."SEQ_SLL" IS '판매자 일련번호';

COMMENT ON COLUMN "TB_SLL"."ID" IS '아이디';

COMMENT ON COLUMN "TB_SLL"."PASSWD" IS '비밀번호';

COMMENT ON COLUMN "TB_SLL"."CD_STATE" IS '상태코드: 대기(0), 사용=승인(1), 반려(2), 자퇴(8), 강퇴(9)';

COMMENT ON COLUMN "TB_SLL"."SLL_NM" IS '판매자 성명';

COMMENT ON COLUMN "TB_SLL"."EMAIL" IS '이메일';

COMMENT ON COLUMN "TB_SLL"."PHONE" IS '연락처';

COMMENT ON COLUMN "TB_SLL"."CORP_NUM" IS '사업자 등록 번호(예: 123-45-67890)';

COMMENT ON COLUMN "TB_SLL"."CORP_NM" IS '회사명(=판매처)';

COMMENT ON COLUMN "TB_SLL"."CORP_BIRTHDAY" IS '개업 년월일(YYYYMMDD)';

COMMENT ON COLUMN "TB_SLL"."CORP_CEO" IS '대표자명';

COMMENT ON COLUMN "TB_SLL"."POST" IS '우편번호';

COMMENT ON COLUMN "TB_SLL"."ADDR1" IS '주소1';

COMMENT ON COLUMN "TB_SLL"."ADDR2" IS '주소2';

COMMENT ON COLUMN "TB_SLL"."INTRO" IS '회사 소개';

COMMENT ON COLUMN "TB_SLL"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_SLL"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_SLL"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_SLL"."UPDATER" IS '수정자';

DROP TABLE "TB_HRT";

CREATE TABLE "TB_HRT" (
	"SEQ_HRT"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(10)		NOT NULL,
	"SEQ_SLE"	NUMBER(10)		NULL,
	"SEQ_ACT"	NUMBER(19)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"FLG_CANCEL"	CHAR(1)		NOT NULL,
	"FLG_SLE_DELETE"	CHAR(1)		NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NOT NULL,
	"UPDATER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_HRT"."SEQ_HRT" IS '좋아요 일련번호';

COMMENT ON COLUMN "TB_HRT"."SEQ_MBR" IS '구매자 열련번호';

COMMENT ON COLUMN "TB_HRT"."SEQ_SLE" IS '상품 판매 일련번호';

COMMENT ON COLUMN "TB_HRT"."SEQ_ACT" IS '경매 일련번호';

COMMENT ON COLUMN "TB_HRT"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_HRT"."FLG_CANCEL" IS '기본: N, 취소: Y';

COMMENT ON COLUMN "TB_HRT"."FLG_SLE_DELETE" IS '상품 삭제 여부: 기본(NULL), 삭제(Y)';

COMMENT ON COLUMN "TB_HRT"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_HRT"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_HRT"."UPDATER" IS '수정자';

DROP TABLE "TB_ACT";

CREATE TABLE "TB_ACT" (
	"SEQ_ACT"	NUMBER(19)		NOT NULL,
	"ACT_NM"	VARCHAR2(256)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"DESCES"	VARCHAR2(2048)		NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"BUY_YEAR"	CHAR(4)		NOT NULL,
	"ACT_STATE"	CHAR(1)		NOT NULL,
	"DT_ACT_START"	DATE		NOT NULL,
	"DT_ACT_END"	DATE		NOT NULL,
	"HEART"	NUMBER(10)		NULL,
	"SUCCESS"	CHAR(1)		NULL,
	"SEQ_MBR"	NUMBER(10)		NULL,
	"CD_STATE_ACT"	CHAR(1)		NOT NULL,
	"REJECT"	VARCHAR(1024)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_ACT"."SEQ_ACT" IS '경매 일련번호';

COMMENT ON COLUMN "TB_ACT"."ACT_NM" IS '경매 상품명';

COMMENT ON COLUMN "TB_ACT"."PRICE" IS '경매 시작 가격';

COMMENT ON COLUMN "TB_ACT"."DESCES" IS '상품 설명';

COMMENT ON COLUMN "TB_ACT"."IMG" IS '경매 상품 대표 이미지';

COMMENT ON COLUMN "TB_ACT"."BUY_YEAR" IS '경매 상품 구매 년도';

COMMENT ON COLUMN "TB_ACT"."ACT_STATE" IS '경매 상품 상태';

COMMENT ON COLUMN "TB_ACT"."DT_ACT_START" IS '경매 시작 일시';

COMMENT ON COLUMN "TB_ACT"."DT_ACT_END" IS '경매 종료 일시';

COMMENT ON COLUMN "TB_ACT"."HEART" IS '좋아요 수';

COMMENT ON COLUMN "TB_ACT"."SUCCESS" IS '낙찰 여부: 낙찰전(NULL), 낙찰(Y), 유찰(N)';

COMMENT ON COLUMN "TB_ACT"."SEQ_MBR" IS '낙찰자 일련번호: 낙찰 전(NULL)';

COMMENT ON COLUMN "TB_ACT"."CD_STATE_ACT" IS '경매 상태 코드: 대기(0), 승인(1)';

COMMENT ON COLUMN "TB_ACT"."REJECT" IS '반려사유: 승인 시(NULL)';

COMMENT ON COLUMN "TB_ACT"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_ACT"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_ACT"."DT_UPT" IS '수정 일시 ( 경매상태코드 = 0 일때만 수정가능)';

COMMENT ON COLUMN "TB_ACT"."UPDATER" IS '수정자';

DROP TABLE "TB_ACT_IMG";

CREATE TABLE "TB_ACT_IMG" (
	"SEQ_ACT_IMG"	NUMBER(19)		NOT NULL,
	"SEQ_ACT"	NUMBER(19)		NOT NULL,
	"IMG"	VARCHAR2(256)		NOT NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_ACT_IMG"."SEQ_ACT_IMG" IS '경매 상품 이미지 일련번호';

COMMENT ON COLUMN "TB_ACT_IMG"."SEQ_ACT" IS '경매 일련번호';

COMMENT ON COLUMN "TB_ACT_IMG"."IMG" IS '이미지';

COMMENT ON COLUMN "TB_ACT_IMG"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_ACT_IMG"."REGISTER" IS '등록자';

DROP TABLE "TB_BID";

CREATE TABLE "TB_BID" (
	"SEQ_BID"	NUMBER(19)		NOT NULL,
	"SEQ_ACT"	NUMBER(19)		NOT NULL,
	"SEQ_MBR"	NUMBER(19)		NOT NULL,
	"BID_PRICE"	NUMBER(10)		NOT NULL,
	"FLG_SUCCESS"	CHAR(1)		NULL,
	"FLG_GIVEUP"	CHAR(1)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL,
	"DT_UPT"	DATE		NULL,
	"UPDATER"	NUMBER(10)		NULL
);

COMMENT ON COLUMN "TB_BID"."SEQ_BID" IS '입찰 일련번호';

COMMENT ON COLUMN "TB_BID"."SEQ_ACT" IS '경매 일련번호';

COMMENT ON COLUMN "TB_BID"."SEQ_MBR" IS '입찰자(회원) 일련번호';

COMMENT ON COLUMN "TB_BID"."BID_PRICE" IS '입찰가';

COMMENT ON COLUMN "TB_BID"."FLG_SUCCESS" IS '낙찰 여부: 기본(NULL), 낙찰(Y), 실패(N)';

COMMENT ON COLUMN "TB_BID"."FLG_GIVEUP" IS '입찰 포기 여부: 기본(NULL), 포기(Y)';

COMMENT ON COLUMN "TB_BID"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_BID"."REGISTER" IS '등록자';

COMMENT ON COLUMN "TB_BID"."DT_UPT" IS '수정 일시';

COMMENT ON COLUMN "TB_BID"."UPDATER" IS '수정자';

DROP TABLE "TB_DLV";

CREATE TABLE "TB_DLV" (
	"SEQ_DLV"	NUMBER(19)		NOT NULL,
	"SEQ_BUY_MST"	NUMBER(19)		NOT NULL,
	"DLV_NM"	VARCHAR2(64)		NOT NULL,
	"PHONE"	VARCHAR2(64)		NOT NULL,
	"POST"	VARCHAR2(64)		NOT NULL,
	"ADDR1"	VARCHAR2(256)		NOT NULL,
	"ADDR2"	VARCHAR2(256)		NOT NULL,
	"MESSAGE"	VARCHAR2(1024)		NULL,
	"DT_REG"	DATE		NOT NULL,
	"REGISTER"	NUMBER(10)		NOT NULL
);

COMMENT ON COLUMN "TB_DLV"."SEQ_DLV" IS '배송 정보 일련번호';

COMMENT ON COLUMN "TB_DLV"."SEQ_BUY_MST" IS '구매 마스터 일련번호';

COMMENT ON COLUMN "TB_DLV"."DLV_NM" IS '수령인 성명';

COMMENT ON COLUMN "TB_DLV"."PHONE" IS '수령인  연락처';

COMMENT ON COLUMN "TB_DLV"."POST" IS '배송지 우편번호';

COMMENT ON COLUMN "TB_DLV"."ADDR1" IS '배송지 주소1';

COMMENT ON COLUMN "TB_DLV"."ADDR2" IS '배송지 주소2';

COMMENT ON COLUMN "TB_DLV"."MESSAGE" IS '요청사항';

COMMENT ON COLUMN "TB_DLV"."DT_REG" IS '등록 일시';

COMMENT ON COLUMN "TB_DLV"."REGISTER" IS '등록자';

DROP TABLE "TB_VST";

CREATE TABLE "TB_VST" (
	"SEQ_VST"	NUMBER(19)		NOT NULL,
	"YEAR"	CHAR(4)		NOT NULL,
	"MONTH"	CHAR(2)		NOT NULL,
	"VISITOR"	NUMBER(19)		NOT NULL
);

COMMENT ON COLUMN "TB_VST"."SEQ_VST" IS '방문자수 일련번호';

COMMENT ON COLUMN "TB_VST"."YEAR" IS '년도';

COMMENT ON COLUMN "TB_VST"."MONTH" IS '월';

COMMENT ON COLUMN "TB_VST"."VISITOR" IS '방문자수';

ALTER TABLE "TB_MBR" ADD CONSTRAINT "PK_TB_MBR" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_TRM_AGR" ADD CONSTRAINT "PK_TB_TRM_AGR" PRIMARY KEY (
	"SEQ_TRM_AGR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "PK_TB_STAT_MBR" PRIMARY KEY (
	"SEQ_MBR"
);

ALTER TABLE "TB_SLE" ADD CONSTRAINT "PK_TB_SLE" PRIMARY KEY (
	"SEQ_SLE"
);

ALTER TABLE "TB_SLE_IMG" ADD CONSTRAINT "PK_TB_SLE_IMG" PRIMARY KEY (
	"SEQ_SLE_IMG"
);

ALTER TABLE "TB_BSK" ADD CONSTRAINT "PK_TB_BSK" PRIMARY KEY (
	"SEQ_BSK"
);

ALTER TABLE "TB_REV" ADD CONSTRAINT "PK_TB_REV" PRIMARY KEY (
	"SEQ_REV"
);

ALTER TABLE "TB_BUY_MST" ADD CONSTRAINT "PK_TB_BUY_MST" PRIMARY KEY (
	"SEQ_BUY_MST"
);

ALTER TABLE "TB_BUY_DTL" ADD CONSTRAINT "PK_TB_BUY_DTL" PRIMARY KEY (
	"SEQ_BUY_DTL"
);

ALTER TABLE "TB_BBS" ADD CONSTRAINT "PK_TB_BBS" PRIMARY KEY (
	"SEQ_BBS"
);

ALTER TABLE "TB_PAY" ADD CONSTRAINT "PK_TB_PAY" PRIMARY KEY (
	"SEQ_PAY"
);

ALTER TABLE "TB_MNG" ADD CONSTRAINT "PK_TB_MNG" PRIMARY KEY (
	"SEQ_MNG"
);

ALTER TABLE "TB_SLL" ADD CONSTRAINT "PK_TB_SLL" PRIMARY KEY (
	"SEQ_SLL"
);

ALTER TABLE "TB_HRT" ADD CONSTRAINT "PK_TB_HRT" PRIMARY KEY (
	"SEQ_HRT"
);

ALTER TABLE "TB_ACT" ADD CONSTRAINT "PK_TB_ACT" PRIMARY KEY (
	"SEQ_ACT"
);

ALTER TABLE "TB_ACT_IMG" ADD CONSTRAINT "PK_TB_ACT_IMG" PRIMARY KEY (
	"SEQ_ACT_IMG"
);

ALTER TABLE "TB_BID" ADD CONSTRAINT "PK_TB_BID" PRIMARY KEY (
	"SEQ_BID"
);

ALTER TABLE "TB_DLV" ADD CONSTRAINT "PK_TB_DLV" PRIMARY KEY (
	"SEQ_DLV"
);

ALTER TABLE "TB_VST" ADD CONSTRAINT "PK_TB_VST" PRIMARY KEY (
	"SEQ_VST"
);

ALTER TABLE "TB_TRM_AGR" ADD CONSTRAINT "FK_TB_MBR_TO_TB_TRM_AGR_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR" (
	"SEQ_MBR"
);

ALTER TABLE "TB_STAT_MBR" ADD CONSTRAINT "FK_TB_MBR_TO_TB_STAT_MBR_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR" (
	"SEQ_MBR"
);

ALTER TABLE "TB_SLE_IMG" ADD CONSTRAINT "FK_TB_SLE_TO_TB_SLE_IMG_1" FOREIGN KEY (
	"SEQ_SLE"
)
REFERENCES "TB_SLE" (
	"SEQ_SLE"
);

ALTER TABLE "TB_REV" ADD CONSTRAINT "FK_TB_BUY_DTL_TO_TB_REV_1" FOREIGN KEY (
	"SEQ_BUY_DTL"
)
REFERENCES "TB_BUY_DTL" (
	"SEQ_BUY_DTL"
);

ALTER TABLE "TB_BUY_DTL" ADD CONSTRAINT "FK_TB_BUY_MST_TO_TB_BUY_DTL_1" FOREIGN KEY (
	"SEQ_BUY_MST"
)
REFERENCES "TB_BUY_MST" (
	"SEQ_BUY_MST"
);

ALTER TABLE "TB_PAY" ADD CONSTRAINT "FK_TB_BUY_MST_TO_TB_PAY_1" FOREIGN KEY (
	"SEQ_BUY_MST"
)
REFERENCES "TB_BUY_MST" (
	"SEQ_BUY_MST"
);

ALTER TABLE "TB_PAY" ADD CONSTRAINT "FK_TB_MBR_TO_TB_PAY_1" FOREIGN KEY (
	"SEQ_MBR"
)
REFERENCES "TB_MBR" (
	"SEQ_MBR"
);

ALTER TABLE "TB_ACT_IMG" ADD CONSTRAINT "FK_TB_ACT_TO_TB_ACT_IMG_1" FOREIGN KEY (
	"SEQ_ACT"
)
REFERENCES "TB_ACT" (
	"SEQ_ACT"
);

ALTER TABLE "TB_BID" ADD CONSTRAINT "FK_TB_ACT_TO_TB_BID_1" FOREIGN KEY (
	"SEQ_ACT"
)
REFERENCES "TB_ACT" (
	"SEQ_ACT"
);

ALTER TABLE "TB_DLV" ADD CONSTRAINT "FK_TB_BUY_MST_TO_TB_DLV_1" FOREIGN KEY (
	"SEQ_BUY_MST"
)
REFERENCES "TB_BUY_MST" (
	"SEQ_BUY_MST"
);

